version: "3"

services:
  next-app:
    container_name: pedemais-app-dev
    build:
      context: .
      dockerfile: dev.Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app
    restart: always
    ports:
      - "3000:3000"
    networks:
      - pedemais_network
  postgres:
    container_name: pedemais-app-postgres
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "54320:5432"
    networks:
      - pedemais_network
volumes:
  postgres-data:

networks:
  pedemais_network:
    driver: bridge